# Generated by Django 3.1.7 on 2021-03-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
