# Generated by Django 3.1.7 on 2021-04-01 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_f_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='f_user',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
