# Generated by Django 3.1.7 on 2021-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210401_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Hashtag'),
        ),
    ]
